### PR TITLE
Move errors from failure to thiserror

### PR DESCRIPTION
**Pull request by phyber**
This PR switches the `failure` crate over to [`thiserror`](https://github.com/dtolnay/thiserror).

### CODE REVIEW

**Comment by phyber** [comment]
The test failures look like it's because they're not running as root.

**Comment by fabianfreyer** [comment]
Yup! Should be fixed now, feel free to rebase (maybe once the tests on `main` have passed)!

**Review by fabianfreyer — APPROVED** [review]

**Comment by phyber** [comment]
Rebased 👍

**Comment by fabianfreyer** [comment]
Thanks!

**Pull request merged**
